apiVersion: v1
kind: Pod
metadata:
  labels:
    name: exclusive 
  generateName: exclusive-
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: exclusive-1
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 1
          memory: 256Mi
        limits:
          cpu: 1
          memory: 256Mi
      securityContext:
        capabilities: {}
        privileged: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    cpumanager: "true"
