apiVersion: v1
kind: Pod
metadata:
  labels:
    name: shared 
  generateName: shared-
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: shared-1
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 100m
      securityContext:
        capabilities: {}
        privileged: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    cpumanager: "true"
