apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpav1
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: hello-openshift
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
