apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: hello-hpa-memory
  name: hello-hpa-memory
spec:
  replicas: 2
  selector:
    run: hello-hpa-memory
  template:
    metadata:
      labels:
        run: hello-hpa-memory
    spec:
      containers:
      - image: docker.io/deshuai/hello-hpa:latest
        imagePullPolicy: IfNotPresent
        name: hello-hpa
        resources:
          requests:
            memory: 200Mi
      restartPolicy: Always
