kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: pods-hpa
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: hello-openshift
    apiVersion: v1
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: cpu
      targetAverageValue: 80
